server:
    port: 8080

minio:
    bucket:
        name: ecp-image
    access:
        key: NMPEZF83o7L6VzMHknZa
        secret: 3Yez28TklgwEcPi6zg1Jte3swNfSePyLseQcCQI6
    url: http://127.0.0.1:9001

spring:
    application:
        name: ecp
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3307/ecp
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                order_inserts: true
                jdbc:
                    batch_size: 50