server:
    port: 8080

minio:
    bucket:
        name: ecp-image
    access:
        key: NMPEZF83o7L6VzMHknZa
        secret: 3Yez28TklgwEcPi6zg1Jte3swNfSePyLseQcCQI6
    url: http://127.0.0.1:9000

id_extract_url: http://127.0.0.1:8082/uploader
file_path: C:/record/

spring:
    application:
        name: ecp
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 20MB
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://127.0.0.1:3307/ecp
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                order_inserts: true
                jdbc:
                    batch_size: 50
    mail:
        host: smtp.gmail.com
        port: 587
        username: doantuanbao2708@gmail.com
        password: knnyiatmmgbrtbdg
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
